# Generated by Django 5.2.4 on 2025-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
