# Generated by Django 5.2.4 on 2025-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_passenger_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='country_code',
            field=models.CharField(default='+353', max_length=6),
            preserve_default=False,
        ),
    ]
