# Generated by Django 5.2.4 on 2025-07-14 12:11

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_passenger_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IE'),
        ),
    ]
