# Generated by Django 5.2.4 on 2025-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0005_remove_passenger_phone_passenger_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('guests', models.IntegerField(default=0)),
                ('time_joined', models.DateTimeField()),
                ('time_called', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
