# Generated by Django 5.2.4 on 2025-07-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0006_passengerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='notification_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=10),
        ),
    ]
