# Generated by Django 5.2.4 on 2025-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0007_passenger_email_passenger_notification_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='notification_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=10),
        ),
    ]
