# Generated by Django 5.2.4 on 2025-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0008_alter_passenger_notification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
