# Generated by Django 5.2.4 on 2025-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0009_passenger_called_passenger_called_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='country_code',
            field=models.CharField(default='+353', max_length=7),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='local_phone',
            field=models.CharField(max_length=35),
        ),
    ]
