# Generated by Django 5.2.4 on 2025-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0010_alter_passenger_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='notification_method',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=10),
        ),
    ]
